### ISSUE TITLE
hey trying this on arch 

### ISSUE THREAD

**Issue by cyrstem** [npisanti/of_vscode#1]
i get this
nojia% of_vscode.sh 
creating project in current path
generating visual studio oF project named RandomPSphere
generating .vscode/c_cpp_properties.json
    adding oF includes
    file ofxGui.paths not present, starting automatic paths finding
        presuming path /home/jacos/of_v0.10.1_linux64gcc6_release/addons/ofxGui
        adding all the paths in /home/jacos/of_v0.10.1_linux64gcc6_release/addons/ofxGui/src
parsing workspace folders...
    adding ofxGui to workspace
editing other json files
copying oF makefile files
running gnu global to generate tags
/usr/local/bin/of_vscode.sh: line 139: gtags: command not found
 how can i fix this ?

**Comment by npisanti** [comment]
did you run `install.sh` before using it? also maybe some paths needs to be changed, does arch uses `/usr/local/bin` as path for bins and scripts?

**Comment by npisanti** [comment]
ah no wait, `gtags command not found` means you don't have gnu global installed in your system, in debian i did `sudo apt-get install global` but i don't know the name for that repo in arch

**Comment by cyrstem** [comment]
yeah   that works awesome!!!
 how do i set code completion if its possible ? and is there a way to change 
and one more thing when i try to  add ofxGui.h  in the ofApp.h 
it gives me this  error 


Compiling axixx for Release
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
/bin/sh: /home/jacos/of_v0.10.1_linux64gcc6_release/addons/obj/linux64/Release/.compiler_flags: Permission denied
make[1]: *** [/home/jacos/of_v0.10.1_linux64gcc6_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:216: /home/jacos/of_v0.10.1_linux64gcc6_release/addons/obj/linux64/Release/.compiler_flags] Error 1
make: *** [/home/jacos/of_v0.10.1_linux64gcc6_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
The terminal process terminated with exit code: 2

**Comment by npisanti** [comment]
code completion should be enabled, after you create the project by running `of_vscode.sh` in the folder of your project, can you please write down what the console says after you run the command?

**Comment by cyrstem** [comment]
yup when i install 

installing of_vscode.sh
```
oF directory set to /home/jacos/of_v20190324_linux64gcc6_release
compiler set to vs code default
sudo password required for moving generated script to /usr/local/bin
and when i run of of_v

```
creating project in current path
generating visual studio oF project named axixx
generating .vscode/c_cpp_properties.json
    adding oF includes
parsing workspace folders...
editing other json files
copying oF makefile files
running gnu global to generate tags
```
but i dont get code completion  like if i type ofSetW....   doest appear the completion and sometimes i 
```

**Comment by npisanti** [comment]
ok, it with that autocompletion should work, please reedit the formatting of the last message as i cannot read some of the things, if the problem is about the autocompletion of the addons you should have an `addons.make` file in your app project folder with the correct addons, otherwise it is strange

**Comment by cyrstem** [comment]
nop sorry i change on settings.json  from default to clang-x64 and it work 
    "C_Cpp.default.intelliSenseMode": "clang-x64",

thanks !

**Comment by npisanti** [comment]
mmm maybe i should default it to clang, thanks for the hint

**Comment by npisanti** [comment]
i updated the repo, now it just sets the intellisense to `clang-x64`

**Comment by cyrstem** [comment]
great ill pull right now

**Comment by cyrstem** [comment]
great ill pull right now
